name: Deploy Website
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: kersvers/s3-sync-with-cloudfront-invalidation@v1.0.0
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_ACCESS_KEY_ID: AKIATD5M2B3UVBWRPOGB
        AWS_SECRET_ACCESS_KEY: 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
        AWS_S3_BUCKET: sdev-test-helper
        DISTRIBUTION_ID: 'ERUXZ17GY5DZX'
        AWS_REGION: 'us-east-1'